name: Build Binaries

on:
  push:
    branches: [master] # Run on master or tags
    tags:
      - "v*"

jobs:
  build_x64_native:
    name: ${{ matrix.os }} Binaries
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        include:
          - os: ubuntu
            runner: ubuntu-20.04
            caxa:
              output: dungeon-revealer-linux
          - os: macos
            runner: macos-latest
            caxa:
              output: dungeon-revealer-macos
          - os: windows
            runner: windows-latest
            caxa:
              output: dungeon-revealer.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Code
        run: |
          npm run build

      - name: Compile x64 binary
        id: compile
        run: |
          mkdir tmp
          mv build/ tmp/
          mv server-build/ tmp/
          mv node_modules/ tmp/
          mv package.json tmp/
          mv package-lock.json tmp/
          cd tmp
          npx caxa --directory . --command "{{caxa}}/node_modules/.bin/node" "{{caxa}}/server-build/index.js" --output "${{ matrix.caxa.output }}"

      - name: Package binary
        run: |
          mkdir dungeon-revealer-${{ matrix.os }}
          mv "tmp/${{ matrix.caxa.output }}" ./dungeon-revealer-${{ matrix.os }}/
          mv ./LICENSE ./dungeon-revealer-${{ matrix.os }}/
          mv ./README.md ./dungeon-revealer-${{ matrix.os }}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dungeon-revealer-${{ matrix.os }}
          path: "dungeon-revealer-${{ matrix.os }}/"

  build_arm:
    name: ${{ matrix.arch }} Binaries
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [linux/arm/v7, linux/arm64/v8]
        include:
          - platform: linux/arm/v7
            arch: armv7
            caxa:
              output: dungeon-revealer-linux-armv7
          - platform: linux/arm64/v8
            arch: arm64
            caxa:
              output: dungeon-revealer-linux-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.arch }}
        run: |
          docker buildx build -f arm-compile.Dockerfile \
            --platform ${{ matrix.platform }} \
            --build-arg CAXA_OUTPUT=${{ matrix.caxa.output }} \
            --load -t dr/bin:${{ matrix.arch }} .
          APP=$(docker run --rm -it -d dr/bin:${{ matrix.arch }})
          docker cp $APP:/usr/src/build/${{ matrix.caxa.output }} ./bin/
          docker kill $APP

      - name: Package binary
        run: |
          mkdir dungeon-revealer-linux-${{ matrix.arch }}
          mv bin/${{ matrix.caxa.output }} ./dungeon-revealer-linux-${{ matrix.arch }}/
          mv ./LICENSE ./dungeon-revealer-linux-${{ matrix.arch }}/
          mv ./README.md ./dungeon-revealer-linux-${{ matrix.arch }}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dungeon-revealer-linux-${{ matrix.arch }}
          path: "dungeon-revealer-linux-${{ matrix.arch }}/"

  job_upload:
    name: Upload Release Assets
    needs: [build_x64_native, build_arm]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          echo "COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GH_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: bin/

      # Zip all artifacts
      - name: Zip Archives
        run: |
          cd bin
          chmod +x ./dungeon-revealer-macos/dungeon-revealer-macos
          chmod +x ./dungeon-revealer-ubuntu/dungeon-revealer-linux
          chmod +x ./dungeon-revealer-linux-armv7/dungeon-revealer-linux-armv7
          chmod +x ./dungeon-revealer-linux-arm64/dungeon-revealer-linux-arm64
          for idir in */;
          do
            (cd "$idir"; rm dungeon-revealer || true; zip -r "../${idir%/}.zip" .);
          done

      - name: Upload Zip Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dungeon-revealer-binaries-${{ github.sha }}
          path: "bin/*.zip"

      - name: Create Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      # We have to upload assets individually using upload-release-asset@v1
      # There isn't a matrix for steps.
      - name: Upload Linux Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/dungeon-revealer-ubuntu.zip
          asset_name: dungeon-revealer-linux-${{ env.GH_TAG }}.zip
          asset_content_type: application/zip

      - name: Upload MacOS Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/dungeon-revealer-macos.zip
          asset_name: dungeon-revealer-macos-${{ env.GH_TAG }}.zip
          asset_content_type: application/zip

      - name: Upload Windows Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/dungeon-revealer-windows.zip
          asset_name: dungeon-revealer-windows-${{ env.GH_TAG }}.zip
          asset_content_type: application/zip

      - name: Upload Linux armv7 Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/dungeon-revealer-linux-armv7.zip
          asset_name: dungeon-revealer-linux-armv7-${{ env.GH_TAG }}.zip
          asset_content_type: application/zip

      - name: Upload Linux arm64 Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./bin/dungeon-revealer-linux-arm64.zip
          asset_name: dungeon-revealer-linux-arm64-${{ env.GH_TAG }}.zip
          asset_content_type: application/zip

      - name: "Set environment for discord"
        if: success() && startsWith( github.ref, 'refs/heads')
        run: |
          # Template json to send as an embed
          # jq replaces $var with `jq --arg var <value> "$TEMPLATE"`
          TEMPLATE='[{"title": $title, "url": $url, "color": $color, "description": $desc}]'

          # Grab the list of commits from event.json
          COMMITS=$(cat $GITHUB_EVENT_PATH | jq -c '.commits')

          # Iterate through each commit and create the formatted string:
          # [`<commit_sha_short>`](<commit_url>) <commit_message>\n <other_commits>
          DESC=''
          for row in $(echo "${COMMITS}" | jq -r '.[] | @base64'); do
              _jq() {
               echo ${row} | base64 --decode | jq -r ${1}
              }
             DESC=$DESC$(printf "[%s](%s) %s" $'`'"$(_jq '.id' | cut -c -7)"$'`' "$(_jq '.url')" "$(_jq '.message')")$'\n'
          done

          # Check if description is longer than the character limit
          if [ ${#DESC} -gt 2048 ]; then
            DESC=$(echo $DESC | cut -c -2045)"..."
          fi
          echo "$DESC"
          echo "DISCORD_EMBEDS=$(jq -nc --arg title "[${{ github.event.repository.name }}:${GITHUB_REF##*/}] binary build" --arg url "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}" --arg color "16750848" --arg desc "$DESC" "$TEMPLATE")" >> $GITHUB_ENV

      - name: Discord notification
        if: success() && startsWith( github.ref, 'refs/heads')
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_UPDATES }}
        uses: Ilshidur/action-discord@0.3.0
