name: Discord master update

on:
  push:
    branches: [master]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Set environment: master"
        run: |
          set -x
          echo "::set-env name=COMMIT_SHORT::$(git rev-parse --short HEAD)"
          echo "::set-env name=DISCORD_EMBEDS::$(jq -nc --arg title "[dungeon-revealer:master] new commit" --arg desc "${{ github.event.head_commit.message }}" --arg url "${{ github.event.head_commit.url }}" '[{"title": $title, "url": $url, "description": $desc}]')"
          echo "${{ github.event.before }}"
          echo "${{ github.event.after }}"
          echo "${{ github.event.compare }}"
          echo "${{ github.event.repository.name }}"
          echo "${{ github.event.ref }}"
          echo "{{ github.event }}"
          echo toJson(github.event.commits)



      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_UPDATES }}
        uses: Ilshidur/action-discord@0.3.0
        with:
          args: "New commit pushed, master@${{ env.COMMIT_SHORT }}: *${{ github.event.head_commit.message }}*\n <${{ github.event.head_commit.url }}>"
